manifest_version = 2
name = "avatar-catalog-proxy"
description = "Roblox avatar + catalog proxy (Compute@Edge)"
language = "javascript"
service_id = ""   # bisa dikosongkan, nanti link saat deploy
